config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'auth/:provider/callback', to: 'posts#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'posts#destroy', as: 'signout'

  resources :posts
  root to: 'static#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  validates_presence_of :date, :uid

  serialize :follows, Array

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitch]

  def self.create_from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :client
  def index

  end

  def new
    @json = @client.get_users_follows(from_id: current_user.uid).data
    @follows = @json.as_json

    @ids = Array.new

    @follows.each do |channelId|
      id = channelId['to_id'].to_i
      @ids.push(id)
    end

    t = Post.create(follows: @ids, uid: current_user, date: Date.today, item: "twitch")
    t.save!

  end

  def client
    @client = Twitch::Client.new(client_id: "qy77chdevync3a4xyrp1o7xpw922qw")
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def homepage
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitch
    @user = User.create_from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitch"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apitester</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <%= render 'shared/nav' %>
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<%#= app/views/pages/indexx.html.erb %>

<% follows = Post.find(51) %>

<% follows.follows.each do |i| %>
    <% p = @client.get_streams({user_id: i}).data %>
    <% j = p.as_json %>
      <% if j[0].nil? %>

        <% else %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= j[0]['title'] %>
          </h3>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <% k = j[0]['thumbnail_url']%>
            <% p = k.sub!("{width}x{height}", "400x225") %>
            <img src=<%= p %>>
          </h3>
        </div>
      </div>
        <% end %>
<% end %>

app/views/shared/_nav.html.erb
  <ul class="nav navbar-nav">
    <li class="active">
      <%= link_to "index", root_path %>
    </li>
    <li>
      <%= link_to "new", new_post_path %>
    </li>
    <li>
      <%= link_to "items", posts_path %>
    </li>
    <li>
      <%= link_to "sign up", new_user_registration_path %>
    </li>
    <li>
      <%= link_to "sign in", new_user_session_path %>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <a href="#">Link</a>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
      <ul class="dropdown-menu">
      </ul>
    </li>
  </ul>